### PR TITLE
fixed typos in part1_02 big O notation #1

### PR DESCRIPTION
**Pull request by ehsan-shadi**

### CODE REVIEW

**Comment by ehsan-shadi** [comment]
Please check the typo corrections #1

**Comment by hamedkvs** [comment]
@ehsan-shadi  have you created the md file using the python script? this should be performed this way as the md files are not supposed to be updated manually. I would merge this as the manual vs automatic thing doesn't really affect final product here as both have the same content.

**Comment by ehsan-shadi** [comment]
@hamedkvs I haven't used the python tool yet. But, I will try it out for the next PR.

**Comment by ehsan-shadi** [comment]
opened #3 for having a tutorial on md file creation

**Pull request merged**
